version: '3'

services:
    mysql:
      image: mysql:5.7
      container_name: mysql
      volumes:
        - "db_data:/var/lib/mysql"
        - "./initdb.d:/docker-entrypoint-initdb.d"
        - "./mysql/my.cnf:/etc/mysql/conf.d/my.cnf"
      ports:
        - 4306:3306
      environment:
        - MYSQL_DATABASE=database
        - MYSQL_ROOT_PASSWORD=password
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=password
      links:
        - mysql
      ports:
        - 8080:80
      volumes:
        - /sessions

volumes:
    db_data:
